FORMAT: 1A
HOST: http://localhost:3000

# LernBMSTU

Система тестирования знаний

# Subject and Lectures [/subjectsandlectures]

## Get All Subject and Lectures [GET]

  + Response 200 (application/json)
    + Attributes
      - subjects: array(
        - subject_id: `1` (number) - ID предмета
        - subject_name: `Нейронные сети` (string) - Название предмета
        - lectures (array[Lectures]))

  + Response 404 (application/json)


## Create new subject with lectures [POST]
  Создание нового предмета с лекциями

  + Request (application/json)
    + Attributes
      - subject_id: `-1` (number)
      - subject_name: `Нейронные сети` (string)
      - lectures (array[LecturesOnCreate]))

  + Response 200

  + Response 400 (application/json)
    + Attributes
      - message: `Неправильная структура json`

  + Response 401 (application/json)

    + Attributes
      - message: `Нет прав доступа`

# User [/user/{id}]

## Get user by id [GET]
  Получить данные пользователя по id

  + Response 200
    + Attributes


# Data Structures

## Lectures (object)
- lectures_id: `1` (number) - ID лекции
- lecture_name: `Введение` (string) - Название предмета
- lecture_path: `/public/lec1.pdf` (string) - Путь к pdf файлу лекции

## LecturesOnCreate (object)
- lectures_id: `-1` (number) - ID лекции
- lecture_name: `Введение` (string) - Название предмета
- lecture_path: `` (string, nullable) - Путь к pdf файлу лекции

## Subject (object)
- subject_id: `1` (number) - ID предмета
- subject_name: `Нейронные сети` (string) - Название предмета
- lectures (array[Lectures]))

## User (object)
-
